#!/usr/bin/env python3
"""python configure.py [--version VERSION]: write build.ninja (and objdiff.json) for VERSION.

A version with config/VERSION/splits.txt builds as decomp-toolkit projects do: the original is split into one object per
unit (tools/split.py), and the executable is linked from the compiled objects of the units whose source is Matching and
the split objects of the others, then checked against the original's SHA-1 (tools/link.py). objdiff compares each unit's
compiled object with its split one. Any other version compares each compiled function with the original's
(tools/compare.py)."""
import argparse
import json
import shlex
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "tools"))
from split import read_splits

# (in release order: the index is VERSION in include/version.h)
VERSIONS = ["GC_1_0", "GC_1_1", "GC_1_1p1", "GC_1_2_5", "GC_1_2_5n", "GC_1_3"]
# (the version the build is configured for unless one is named)
PRIMARY = "GC_1_2_5"
# (units the runtime library ships as objects)
LIBRARY_OBJECTS = {"cexc.obj": "lib/runtime/cexc.obj", "ccinit.obj": "lib/runtime/ccinit.obj"}


def pro4_arguments(args):
    """Pro 4's driver takes Microsoft-style options."""
    result, rest = [], iter(args)
    for arg in rest:
        if arg == "-o":
            result.append("/Fo" + next(rest))
        elif arg.startswith("-"):
            result.append("/" + arg[1:])
        else:
            result.append(arg)
    return result


def matching(config, sources, source):
    """Whether SOURCE is Matching in a version: a version can list its Matching sources itself (its config's
    "matching"), else config/sources.json's status decides."""
    if "matching" in config:
        return source in config["matching"]
    return sources[source].get("status", "Matching") == "Matching"


def objdiff(version, config, sources, units):
    """objdiff's project: each unit's split object, the compiled one when it has a source."""
    entries = []
    for unit in units:
        library = unit.startswith(("src/msl/", "src/runtime/")) or unit in LIBRARY_OBJECTS
        entry = dict(name=unit.removeprefix("src/").rsplit(".", 1)[0] if unit.startswith("src/") else unit,
                     target_path=f"build/{version}/obj/{unit}.obj",
                     metadata=dict(complete=unit in LIBRARY_OBJECTS, progress_categories=["runtime" if library else "compiler"]))
        if unit in sources:
            entry["base_path"] = f"build/{version}/compiled/{unit}.obj"
            entry["metadata"].update(complete=matching(config, sources, unit), source_path=unit)
        elif unit in LIBRARY_OBJECTS:
            entry["base_path"] = LIBRARY_OBJECTS[unit]
        else:
            # (the build stamp, the linker's COMMON block, the import library's thunks: no source)
            entry["metadata"]["auto_generated"] = True
        entries.append(entry)
    Path("objdiff.json").write_text(json.dumps({
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "min_version": "3.8.0",
        "custom_make": "ninja",
        "build_target": False,
        "build_base": True,
        "watch_patterns": ["src/**/*.c", "src/**/*.cpp", "include/**/*.h", "config/**/*.json", "config/**/*.txt"],
        "units": entries,
        "progress_categories": [{"id": "compiler", "name": "Compiler"}, {"id": "runtime", "name": "MSL and runtime"}],
    }, indent=2) + "\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", choices=VERSIONS, default=PRIMARY)
    version = parser.parse_args().version
    config = json.loads(Path(f"config/{version}/config.json").read_text())
    sources = json.loads(Path("config/sources.json").read_text())
    splits = Path(f"config/{version}/splits.txt")
    python = shlex.quote(sys.executable)
    out = [
        "# Generated by configure.py",
        f"python = {python}",
        "wibo = build/tools/wibo",
        "",
        "pool downloads",
        "  depth = 1",
        "rule download",
        "  command = $python tools/download_tool.py $tool $out",
        "  description = DOWNLOAD $out",
        "  pool = downloads",
        "rule mwcc",
        # (-MD writes <stem>.dep to the working directory)
        "  command = MWCIncludes=include/libc $wibo $compiler $cflags -MD $in -o $out"
        " && $python tools/transform_dep.py $stem.dep $out",
        "  description = MWCC $in",
        "  depfile = $out.d",
        "  deps = gcc",
        "rule mwcc_pro4",
        "  command = MWCIncludes=include/libc $wibo $compiler $cflags",
        "  description = MWCC $in",
        "rule configure",
        f"  command = $python configure.py --version {version}",
        "  generator = 1",
        "",
        f"version = {version}",
        "build build/tools/objdiff-cli: download",
        "  tool = objdiff-cli",
        "build build/tools/wibo: download",
        "  tool = wibo",
        "build build/compilers/ok "
        + " ".join(json.loads(Path(f"config/{v}/config.json").read_text())["original"] for v in VERSIONS)
        + ": download",
        "  tool = compilers",
    ]
    out += ["build lib/ok: download", "  tool = lib"]
    # (a version built with other compilers or options maps the sources' to its own: config/<version>/config.json
    # "compilers", and "flags", option by option)
    host = lambda settings: config.get("compilers", {}).get(settings["compiler"], settings["compiler"])
    flag = lambda option: config.get("flags", {}).get(option, option)
    for compiler in sorted({host(s) for s in sources.values()}):
        out += [f"build build/compilers/{compiler}/mwcc.exe: download", f"  tool = {compiler}"]
    objects = []
    for source, settings in sources.items():
        obj = f"build/{version}/compiled/{source}.obj"
        compiler = f"build/compilers/{host(settings)}/mwcc.exe"
        args = ["-c", *map(flag, settings["flags"]), f"-DVERSION={VERSIONS.index(version)}",
                *(f"-I{d}" for d in settings.get("include_dirs", [])), "-Iinclude", "-i-",
                *(f"-I{d}" for d in settings.get("system_include_dirs", [])), "-Iinclude/libc"]
        if host(settings) == "pro4":
            out += [f"build {obj}: mwcc_pro4 {source} | $wibo {compiler} || lib/ok",
                    f"  cflags = {shlex.join(pro4_arguments([*args, source, '-o', obj]))}"]
        else:
            out += [f"build {obj}: mwcc {source} | $wibo {compiler} || lib/ok", f"  cflags = {shlex.join(args)}",
                    f"  stem = {Path(source).stem}"]
        out.append(f"  compiler = {compiler}")
        objects.append(obj)
    if splits.exists():
        units = [unit for unit, _ in read_splits(splits)[1]]
        split_objects = [f"build/{version}/obj/{unit}.obj" for unit in units]
        inputs = [f"build/{version}/obj/sections.obj"]
        for unit in units:
            if unit in LIBRARY_OBJECTS:
                inputs.append(LIBRARY_OBJECTS[unit])
            elif unit in sources and matching(config, sources, unit):
                inputs.append(f"build/{version}/compiled/{unit}.obj")
            else:
                inputs.append(f"build/{version}/obj/{unit}.obj")
        inputs += ["lib/win32sdk/KERNEL32.LIB", "build/lmgr326b.lib"]
        out += [
            "rule split",
            "  command = $python tools/split.py $version",
            "  description = SPLIT $version",
            "rule implib",
            "  command = $python tools/implib.py $in $out",
            "  description = IMPLIB $out",
            "rule link",
            "  command = $python tools/link.py $version $out $in",
            "  description = LINK $out",
            "rule report",
            "  command = build/tools/objdiff-cli report generate -o $out",
            "  description = REPORT $version",
            "build build/compilers/pro53/mwld.exe: download",
            "  tool = mwld",
            f"build build/{version}/obj/ok build/{version}/obj/sections.obj {' '.join(split_objects)}: split | "
            f"{config['original']} config/{version}/config.json config/{version}/symbols.txt {splits} "
            "tools/split.py tools/pe.py",
            "build build/lmgr326b.lib: implib config/lmgr326b.def | tools/implib.py",
            f"build build/{version}/mwcceppc.exe | build/{version}/ok: link {' '.join(inputs)} | "
            "$wibo build/compilers/pro53/mwld.exe tools/link.py || lib/ok",
            f"build build/{version}/report.json: report | build/{version}/ok build/tools/objdiff-cli "
            f"{' '.join(objects)}",
        ]
        objdiff(version, config, sources, units)
    else:
        configs = (f"config/{version}/config.json config/{version}/functions.json config/{version}/bindings.json "
                   "config/sources.json")
        out += [
            "rule extract",
            "  command = $python tools/compare.py extract $version",
            "  description = EXTRACT $version",
            "rule compare",
            "  command = $python tools/compare.py compare $version",
            "  description = COMPARE $version",
            "rule report",
            "  command = $python tools/compare.py report $version",
            "  description = REPORT $version",
            f"build build/{version}/target/ok: extract | {config['original']} {configs} tools/compare.py tools/pe.py",
            f"build build/{version}/ok objdiff.json: compare | build/{version}/target/ok {' '.join(objects)}",
            f"build build/{version}/report.json: report | build/{version}/ok build/tools/objdiff-cli",
        ]
    out += [
        f"build all_source: phony {' '.join(objects)}",
        f"build progress: phony build/{version}/report.json",
        f"build build.ninja: configure | configure.py config/sources.json config/{version}/config.json"
        + (f" {splits}" if splits.exists() else ""),
        f"default build/{version}/ok all_source",
        "",
    ]
    Path("build.ninja").write_text("\n".join(out))


if __name__ == "__main__":
    main()
